name = "ShapefileToGmsh"
uuid = "2e053855-5844-441f-8c9c-7f6fb193f5ff"
authors = ["Jordi Manyer"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
