"""
Gmsh geometry file writer.

`write_geo` produces a Gmsh `.geo` script that can be opened in the Gmsh GUI
or meshed from the command line with:

    gmsh output.geo -2

The file uses only built-in Gmsh kernel constructs (no OpenCASCADE dependency),
so it is readable and easy to hand-edit.

Orientation convention (required by Gmsh):
- Exterior curve loops are CCW (positive signed area, Gmsh expects this).
- Hole curve loops are CW (Gmsh subtracts them from the surface).

Because `ShapeGeometry` already normalises ring orientation (see `shapefiles.jl`),
lines are always written in the stored point order and curve loops always use
positive line indices.
"""

# ============================================================================
# Public API
# ============================================================================

"""
    write_geo(geoms, name; mesh_size=1.0, mesh_algorithm=nothing,
              split_components=false)

Write `geoms` to a Gmsh `.geo` script.  `name` should be given **without** the
`.geo` extension — it is always appended internally.

When `split_components = false` (default), all geometries are written into a
single file `name.geo`.

When `split_components = true`, one `.geo` file per `ShapeGeometry` is written
into a directory named `name/`.  Files inside are named `1.geo`, `2.geo`, … .

# Keyword arguments
- `mesh_size`        — characteristic element length assigned to every point.
- `mesh_algorithm`   — optional integer passed as `Mesh.Algorithm` (e.g. 5 =
                       Delaunay, 6 = Frontal-Delaunay, 8 = Frontal-Quad).
                       Omitted from the file when `nothing`.
- `split_components` — write one file per geometry component (default `false`).
"""
function write_geo(
  geoms            :: Vector{ShapeGeometry},
  name             :: AbstractString;
  mesh_size        :: Real               = 1.0,
  mesh_algorithm   :: Union{Int,Nothing} = nothing,
  split_components :: Bool               = false,
)
  if split_components
    _write_geo_split(geoms, name; mesh_size, mesh_algorithm)
  else
    _write_geo_single(geoms, name * ".geo"; mesh_size, mesh_algorithm)
  end
  return name
end

# ============================================================================
# Internal helpers
# ============================================================================

# Write all geometries into one file.
function _write_geo_single(
  geoms          :: Vector{ShapeGeometry},
  path           :: AbstractString;
  mesh_size      :: Real,
  mesh_algorithm,
)
  lc = Float64(mesh_size)
  open(path, "w") do io
    _write_header(io, length(geoms), mesh_algorithm)
    pt_id   = 1
    line_id = 1
    loop_id = 1
    surf_id = 1
    for g in geoms
      pt_id, line_id, loop_id, surf_id =
        _write_geometry(io, g, pt_id, line_id, loop_id, surf_id, lc)
    end
  end
end

# Write one file per geometry component into a directory named `name`.
function _write_geo_split(
  geoms          :: Vector{ShapeGeometry},
  name           :: AbstractString;
  mesh_size      :: Real,
  mesh_algorithm,
)
  mkpath(name)
  nd = ndigits(length(geoms))
  for (i, g) in enumerate(geoms)
    fname = joinpath(name, lpad(i, nd, '0') * ".geo")
    _write_geo_single([g], fname; mesh_size, mesh_algorithm)
  end
end

function _write_header(io::IO, ngeoms::Int, mesh_algorithm)
  println(io, "// Generated by ShapefileToGmsh.jl")
  println(io, "// $(ngeoms) surface(s)")
  if !isnothing(mesh_algorithm)
    println(io, "Mesh.Algorithm = $mesh_algorithm;")
  end
  println(io)
end

# Write one ShapeGeometry (exterior + holes) and return updated counters.
function _write_geometry(io, g, pt_id, line_id, loop_id, surf_id, lc)
  # -- exterior ring -----------------------------------------------------------
  ext_line_ids, pt_id, line_id =
    _write_contour(io, g.exterior, pt_id, line_id, lc, "exterior")
  ext_loop_id = loop_id
  println(io, "Curve Loop($loop_id) = {$(join(ext_line_ids, ", "))};")
  loop_id += 1

  # -- hole rings --------------------------------------------------------------
  hole_loop_ids = Int[]
  for (k, hole) in enumerate(g.holes)
    hole_line_ids, pt_id, line_id =
      _write_contour(io, hole, pt_id, line_id, lc, "hole $k")
    # Hole loops must be oriented CW in Gmsh → negate line indices.
    cw_ids = reverse(-1 .* hole_line_ids)
    println(io, "Curve Loop($loop_id) = {$(join(cw_ids, ", "))};")
    push!(hole_loop_ids, loop_id)
    loop_id += 1
  end

  # -- surface -----------------------------------------------------------------
  all_loops = vcat(ext_loop_id, hole_loop_ids)
  println(io, "Plane Surface($surf_id) = {$(join(all_loops, ", "))};")
  surf_id += 1
  println(io)

  return pt_id, line_id, loop_id, surf_id
end

# Write the points and lines for one contour.  Returns (line_ids, new_pt_id,
# new_line_id) where line_ids is the ordered list of line tags for the contour.
function _write_contour(
  io      :: IO,
  c       :: Contour,
  pt_id   :: Int,
  line_id :: Int,
  lc      :: Float64,
  label   :: AbstractString,
)
  pts = c.points
  n   = length(pts)
  println(io, "// $label ($n points)")

  # -- Points ------------------------------------------------------------------
  first_pt_id = pt_id
  for pt in pts
    @printf(io, "Point(%d) = {%.15g, %.15g, 0, %.15g};\n",
            pt_id, pt[1], pt[2], lc)
    pt_id += 1
  end

  # -- Lines -------------------------------------------------------------------
  nedges   = c.closed ? n : n - 1
  line_ids = Int[]
  for i in 1:nedges
    p_start = first_pt_id + i - 1
    p_end   = c.closed ? first_pt_id + mod(i, n) : first_pt_id + i
    println(io, "Line($line_id) = {$p_start, $p_end};")
    push!(line_ids, line_id)
    line_id += 1
  end
  println(io)

  return line_ids, pt_id, line_id
end
